require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
require("core.plugin_config.copilot")
require("core.plugin_config.dap_config")
require("core.plugin_config.oil")
require("core.plugin_config.transparant")
require("core.plugin_config.hop")
require("core.plugin_config.nvim-comment")
-- require("core.plugin_config.tabout")
require("core.plugin_config.trouble")
